Enrich/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('search.urls')),
    url(r'^organization/', include('organization.urls')),
    url(r'^search/', include('search.urls')),
    url(r'^login/', include('login.urls')),
    url(r'^user/', include('user.urls')),
]

search/urls.py
'''
Routing
'''
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^search_result/$', views.search_result, name="search_result")
]

user/urls.py
"""user urls"""


from django.conf.urls import url
from . import views

urlpatterns = [

]

search/models.py
'''
Models: None needed for Search Functionality
'''
from __future__ import unicode_literals
from django.db import models

# Create your models here.

search/forms.py
'''
Search form input
'''
from django import forms

class SearchForm(forms.Form):
    '''
    Defining the input fields for Search Navbar
    Defined Here, but not templated for HTML and Stlying Reasons
    '''

    search_term = forms.CharField(label="", max_length=100)

    CATEGORYCHOICES = [
        ('STEM', 'STEM'),
        ('Arts/Humanities', 'Arts/Humanities'),
        ('Academic Prep', 'Academic Prep'),
        ('Sports', 'Sports')]
    category = forms.MultipleChoiceField(choices=CATEGORYCHOICES, widget=forms.CheckboxSelectMultiple(), required=False)

    PRICECHOICES = [
        ('TUITION', 'TUITION')]
    price = forms.ChoiceField(choices=PRICECHOICES, widget=forms.RadioSelect(), required=False)



class FilterSearchForm(forms.Form):
    '''
    Defining the input fields for Filter Search
    Defined Here, but not templated for HTML and Stlying Reasons
    '''
    CATEGORYCHOICES = [
        ('STEM', 'STEM'),
        ('Arts/Humanities', 'Arts/Humanities'),
        ('Academic Prep', 'Academic Prep'),
        ('Sports', 'Sports')]
    PRICECHOICES = [
        ('TUITION', 'TUITION')]

    search_term = forms.CharField(label="", max_length=100)
    category = forms.MultipleChoiceField(choices=CATEGORYCHOICES, widget=forms.CheckboxSelectMultiple())
    price = forms.ChoiceField(choices=PRICECHOICES, widget=forms.RadioSelect())

search/views.py
"""Rendering the appropriate views"""

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.db.models import Q
from organization.models import Organization
from user.models import EnrichUser
from .forms import SearchForm, FilterSearchForm

def index(request):
    """Search Form and Get Response"""
    form = SearchForm()
    filterform = FilterSearchForm()
    #user = request.user
    return render(request, 'search/search.html', {'form' : form, 'filterForm' : filterform})

def search_result(request):
    """Display search results"""
    # Check if POST request
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            # get the categoryChoices the user selected
            categoryChoices = form.cleaned_data.get('category')
            priceChoice = form.cleaned_data.get('price')
            #process data and render search results
            query = form.cleaned_data['search_term']
            # Create complex query with Q objects from category choices that the user selected
            # Utilize complex lookups with Q objects
            # https://docs.djangoproject.com/en/dev/topics/db/queries/#complex-lookups-with-q-objects
            if len(categoryChoices) > 0:
                categorySelected = '('
                for choice in categoryChoices:
                    categorySelected += ' Q(category=' + "\'" + choice + "\'" + ') |'
                categorySelected = categorySelected[:-1]
                categorySelected += ')'
                if len(priceChoice) != 0: #Check if program if free
                    results = Organization.objects.filter(Q(description__contains=query, free=False) & eval(categorySelected))
                else:
                    results = Organization.objects.filter(Q(description__contains=query) & eval(categorySelected))
            else:
                if len(priceChoice) != 0: #Check if program if free
                    results = Organization.objects.filter(description__contains=query, free=False)
                else:
                    results = Organization.objects.filter(description__contains=query)

            # starRange and negativeStarRange to render stars
            for result in results:
                rating = result.rating
                result.starRange = range(int(rating))
                result.negativeStarRange = range(5 - int(rating))
            return render(request, 'search/search_results.html', {'search_term': query, 'results':results})
        else:
            results = Organization.objects.all()
            for each in results:
                rating = each.rating
                each.starRange = range(int(rating))
                each.negativeStarRange = range(5 - int(rating))
            return render(request, 'search/search_results.html', {'search_term': ' ', 'results':results})
    else:
        return HttpResponseRedirect('/search/')

search/templates/search/search.html
{% extends "search/search_base.html" %}

{% block content %}
<link rel="stylesheet" href="/static/css/search.css">
<div class="container container-table">
    <div class="row vertical-center-row">
        <div class="text-center col-md-8 col-md-offset-2">
            <form action="/search/search_result/" method="post">
                {% csrf_token %}
                <div class="row">
                    <input class="form-control pull-left input-lg" id="id_search_term" maxlength="100" name="search_term" type="text" required pattern=".*\S+.*" placeholder="Eg. Brooklyn, math, college, piano" style="display:inline-block; width: calc(100% - 100px);">
                    <button type="submit" class="btn btn-success btn-lg pull-right" id="filter_submit">Search</button>
                </div>

                <div class="row">
                    <button type="button" class="btn btn-default pull-left btn-lg col-md-2 text-center check_button_margin" id="STEM_button">STEM</button>
                    <button type="button" class="btn btn-default pull-left btn-lg col-md-2 text-center check_button_margin" id="arts_button">Arts</button>
                    <button type="button" class="btn btn-default pull-left btn-lg col-md-2 text-center check_button_margin"id="academic_button">Academic</button>
                    <button type="button" class="btn btn-default pull-left btn-lg col-md-2 text-center check_button_margin" id="sports_button">Sports</button>
                    <button type="button" class="btn btn-default pull-right btn-lg col-md-2 text-center check_button_margin" id="tuition_button">Tuition</button>
                </div>

                <div style="display:none;">
                    <label for="id_category_0">Category:</label>
                    <ul id="id_category">
                        <li>
                            <label for="id_category_0"><input id="id_category_0" name="category" type="checkbox" value="STEM"> STEM</label>
                        </li>

                        <li>
                            <label for="id_category_1"><input id="id_category_1" name="category" type="checkbox" value="Arts/Humanities"> Arts/Humanities</label>
                        </li>

                        <li>
                            <label for="id_category_2"><input id="id_category_2" name="category" type="checkbox" value="Academic Prep"> Academic Prep</label>
                        </li>

                        <li>
                            <label for="id_category_3"><input id="id_category_3" name="category" type="checkbox" value="Sports"> Sports</label>
                        </li>
                    </ul>

                    <label for="id_price_0">Price:</label>
                    <ul id="id_price">
                        <li>
                            <label for="id_price_0"><input id="id_price_0" name="price" type="checkbox" value="TUITION"> TUITION</label>
                        </li>
                    </ul>
                </div>

            </form>
        </div>
    </div>
</div>

<script src="/static/js/search.js" defer></script>
{% endblock content %}

search/templates/search/search_base.html
{% extends "Enrich/base.html" %}

search/templates/search/search_results.html
{% extends "search/search_base.html" %}

{% block content %}

<div class="container" style="margin-top:70px;">

    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">{{search_term}}
            </h1>
        </div>
    </div>

    {% for result in results %}
    <div class="row">
        <div class="col-md-7">
            <a href="/organization/{{ result.name }}">
                <div class="img-wrap" style="overflow:hidden; height:300px;"><img class="img-responsive" src="{{result.imageURL}}" alt="" style="height:auto; width:700px;"></div>
            </a>
        </div>
        <div class="col-md-5">
            <h3>{{ result.name }}</h3>
            <h4>{{ result.category }}</h4>
            <h5>
                {% for i in result.starRange %}
                    <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                {% endfor %}
                {% for i in result.negativeStarRange %}
                    <span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>
                {% endfor %}
            </h5>
            <p>{{ result.description }}</p>
            <a class="btn btn-primary" href="/organization/{{ result.name }}">View Organization <span class="glyphicon glyphicon-chevron-right"></span></a>
        </div>
    </div>

    <hr>
    {% endfor %}

    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright © Enrich 2016</p>
            </div>
        </div>
    </footer>

</div>


{% endblock content %}